In [1]:
import numpy as np
# creating numpy arrays

# Creating a 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1d)

1D Array: [1 2 3 4 5]


In [2]:
# Creating a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2d)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [3]:
# Creating an array filled with zeros
zeros_arr = np.zeros((3, 4))  # 3 rows, 4 columns
print("Zeros Array:\n", zeros_arr)

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
# Creating an array filled with ones
ones_arr = np.ones((2, 2))
print("Ones Array:\n", ones_arr)

Ones Array:
 [[1. 1.]
 [1. 1.]]


In [5]:
# Creating an array with a range of values
range_arr = np.arange(0, 10, 2)  # Start, stop, step
print("Range Array:", range_arr)

Range Array: [0 2 4 6 8]


In [6]:
# Creating an array with evenly spaced values
linspace_arr = np.linspace(0, 1, 5)  # Start, stop, number of points
print("Linspace Array:", linspace_arr)

Linspace Array: [0.   0.25 0.5  0.75 1.  ]


In [7]:
# array indexing and slicing
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [8]:

# Accessing elements
print("Element at [0, 1]:", arr[0, 1])  # Row 0, column 1


Element at [0, 1]: 20


In [9]:

# Slicing rows
print("Row 1:", arr[1, :])


Row 1: [40 50 60]


In [10]:

# Slicing columns
print("Column 2:", arr[:, 2])


Column 2: [30 60 90]


In [11]:

# Slicing a sub-array
print("Sub-array:\n", arr[1:3, 0:2])

Sub-array:
 [[40 50]
 [70 80]]


In [12]:
# array operations

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition
print("Addition:", arr1 + arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Scalar multiplication
print("Scalar Multiplication:", arr1 * 2)

# Dot product
print("Dot Product:", np.dot(arr1, arr2))

# Sum of all elements
print("Sum:", np.sum(arr1))

# Mean of all elements
print("Mean:", np.mean(arr1))

# Standard deviation
print("Standard Deviation:", np.std(arr1))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Scalar Multiplication: [2 4 6]
Dot Product: 32
Sum: 6
Mean: 2.0
Standard Deviation: 0.816496580927726


In [13]:
import numpy as np

arr = np.arange(1, 10)

# Reshaping
reshaped_arr = arr.reshape((3, 3))
print("Reshaped Array:\n", reshaped_arr)

# Transposing
transposed_arr = reshaped_arr.T
print("Transposed Array:\n", transposed_arr)

Reshaped Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed Array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [13]:
# random number generation

import numpy as np

# Random numbers from a uniform distribution
random_uniform = np.random.rand(2, 3)
print("Random Uniform:\n", random_uniform)

# Random numbers from a normal distribution
random_normal = np.random.randn(2, 3)
print("Random Normal:\n", random_normal)

# Random integers
random_integers = np.random.randint(0, 10, (3, 3))
print("Random Integers:\n", random_integers)

Random Uniform:
 [[0.88464225 0.37306611 0.67064503]
 [0.79370562 0.93717092 0.93317189]]
Random Normal:
 [[ 0.96890719  0.73386191  0.22310314]
 [ 1.31587755 -0.79666198 -0.25057913]]
Random Integers:
 [[5 8 8]
 [5 8 0]
 [8 0 5]]


In [2]:
#opencv 
# Importing the OpenCV library
import cv2
# Reading the image using imread() function
image = cv2.imread('/Users/apitchai002/Documents/Clones/python_packages/data/Arish_p_low_res.jpeg')

# Extracting the height and width of an image
h, w = image.shape[:2]
# Displaying the height and width
print("Height = {}, Width = {}".format(h, w))


Height = 1024, Width = 990


In [15]:
# Extracting RGB values.
# Here we have randomly chosen a pixel
# by passing in 100, 100 for height and width.
(B, G, R) = image[100, 100]

# Displaying the pixel values
print("R = {}, G = {}, B = {}".format(R, G, B))

# We can also pass the channel to extract
# the value for a specific channel
B = image[100, 100, 0]
print("B = {}".format(B))

R = 228, G = 227, B = 232
B = 232


In [ ]:
# We will calculate the region of interest
# by slicing the pixels of the image
roi = image[100 : 500, 200 : 700]
cv2.imshow("ROI", roi)
cv2.waitKey(0)

2025-03-15 08:10:09.634 Python[80183:14694313] +[IMKClient subclass]: chose IMKClient_Modern
2025-03-15 08:10:09.634 Python[80183:14694313] +[IMKInputSession subclass]: chose IMKInputSession_Modern


In [ ]:
# pillow package
from PIL import Image


# Location of the image
img = Image.open("/Users/apitchai002/Documents/Clones/python_packages/data/Arish_p_low_res.jpeg")

img.show()


In [3]:

# size of the image
print(img.size)

# format of the image
print(img.format)


(990, 1024)
JPEG


In [4]:

# mode of the image
print(img.mode)


RGB


In [5]:
import PIL


# rotating a image 90 deg counter clockwise
img = img.rotate(90, PIL.Image.NEAREST, expand = 1)

# to show specified image
img.show()
