In [2]:
from bs4 import BeautifulSoup
import requests

In [8]:
url = "https://www.thehindu.com/"
response = requests.get(url)

In [4]:
soup = BeautifulSoup(response.content, "html.parser")

In [5]:
titles = [item.text.strip() for item in soup.find_all("h2")] #Change to your website structure.

In [6]:
titles

['Parliament Budget Session: DMK attacks Centre over NEP implementation; Nadda calls out Oppn. for adjournment motion notices',
 'Clashes erupt in Madhya Pradesh’s Mhow over rally celebrating India’s Champions Trophy',
 'What to know ahead of talks between U.S., Ukraine in Saudi Arabia',
 'Latest News',
 'Top Videos',
 'Top Picks',
 'The Hindu Opinion',
 'The Hindu Explains',
 'Top News Today',
 'Featured',
 'States Updates',
 'Cities Updates']

In [ ]:
import numpy as np
# creating numpy arrays

# Creating a 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1d)

1D Array: [1 2 3 4 5]


In [2]:
# Creating a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2d)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [3]:
# Creating an array filled with zeros
zeros_arr = np.zeros((3, 4))  # 3 rows, 4 columns
print("Zeros Array:\n", zeros_arr)

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
# Creating an array filled with ones
ones_arr = np.ones((2, 2))
print("Ones Array:\n", ones_arr)

Ones Array:
 [[1. 1.]
 [1. 1.]]


In [5]:
# Creating an array with a range of values
range_arr = np.arange(0, 10, 2)  # Start, stop, step
print("Range Array:", range_arr)

Range Array: [0 2 4 6 8]


In [6]:
# Creating an array with evenly spaced values
linspace_arr = np.linspace(0, 1, 5)  # Start, stop, number of points
print("Linspace Array:", linspace_arr)

Linspace Array: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
# array indexing and slicing
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [8]:

# Accessing elements
print("Element at [0, 1]:", arr[0, 1])  # Row 0, column 1


Element at [0, 1]: 20


In [9]:

# Slicing rows
print("Row 1:", arr[1, :])


Row 1: [40 50 60]


In [10]:

# Slicing columns
print("Column 2:", arr[:, 2])


Column 2: [30 60 90]


In [11]:

# Slicing a sub-array
print("Sub-array:\n", arr[1:3, 0:2])

Sub-array:
 [[40 50]
 [70 80]]


In [ ]:
# array operations

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition
print("Addition:", arr1 + arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Scalar multiplication
print("Scalar Multiplication:", arr1 * 2)

# Dot product
print("Dot Product:", np.dot(arr1, arr2))

# Sum of all elements
print("Sum:", np.sum(arr1))

# Mean of all elements
print("Mean:", np.mean(arr1))

# Standard deviation
print("Standard Deviation:", np.std(arr1))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Scalar Multiplication: [2 4 6]
Dot Product: 32
Sum: 6
Mean: 2.0
Standard Deviation: 0.816496580927726


In [13]:
import numpy as np

arr = np.arange(1, 10)

# Reshaping
reshaped_arr = arr.reshape((3, 3))
print("Reshaped Array:\n", reshaped_arr)

# Transposing
transposed_arr = reshaped_arr.T
print("Transposed Array:\n", transposed_arr)

Reshaped Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed Array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [14]:
# random number generation

import numpy as np

# Random numbers from a uniform distribution
random_uniform = np.random.rand(2, 3)
print("Random Uniform:\n", random_uniform)

# Random numbers from a normal distribution
random_normal = np.random.randn(2, 3)
print("Random Normal:\n", random_normal)

# Random integers
random_integers = np.random.randint(0, 10, (3, 3))
print("Random Integers:\n", random_integers)

Random Uniform:
 [[0.84650865 0.4230645  0.00662783]
 [0.1055365  0.84514502 0.60244275]]
Random Normal:
 [[ 0.05007424 -0.46252423 -0.69663068]
 [ 0.2272313   0.1938236   1.42315433]]
Random Integers:
 [[4 1 3]
 [9 0 6]
 [1 1 6]]
